### ISSUE TITLE
Decoding Error Handling

### ISSUE THREAD

**Issue by dbertouille** [getconversio/go-shopify#74] opened 2018-04-19 21:31 UTC
I'm currently struggling to find a good way to find more information about an error I am seeing. 

`invalid character '<' looking for beginning of value`

It appears that HTML is being returned. However, I can't find a way to get more information since it is intermittent and I can not manually reproduce it.

What would people think about a custom error on decoding errors. This error would contain the response body and HTTP status code to help in tracking down the issue. Something along the lines of,

```
type ResponseDecodingError struct {
	Message          string
	HTTPResponseBody []byte
	HTTPResponseCode int
}
```

I feel like this should contain enough information to allow debugging of errors that the library cannot handle.

Open to thoughts on if there is a better way to handle this.

**Comment by dlebech** [comment] 2018-04-24 17:44
@dbertouille I've also seen this a few times in the past, it's an annoying issue. I assume it happens [here](https://github.com/getconversio/go-shopify/blob/d89fb0a0468afc2bbc7cb1ad93652809838f810a/goshopify.go#L191-L193) right?

Your proposal would be an easy way to get debugging information for sure, so I think it would be a good addition (see also below). I would suggest renaming `HTTPResponseCode` to `Status` and `HTTPResponseBody` to `Body` to be more in line with the naming of the existing [response error](https://github.com/getconversio/go-shopify/blob/fcd5dd4cd9d86f7c50e119522fb1a6553cfc8cfe/goshopify.go#L68) (but not embedding it, probably) and the normal http response in Golang. What do you think?

Just as a sidenote, an entirely other proposal for debugging purposes could be to add a simple logger interface with a simple `Debug(...)` function to begin with that look like the basic `log.Logger` type in Golang. This interface could be added to the to the [`Client`](https://github.com/getconversio/go-shopify/blob/fcd5dd4cd9d86f7c50e119522fb1a6553cfc8cfe/goshopify.go#L35) struct and then you can supply it with your own logger that supports the logging interface (probably `log.Logger` in most cases or perhaps logrus). When the logger is non-nil, things like decoding errors could be logged at the debug level. Just a thought.

Thanks for bringing this up :beers:

**Comment by dlebech** [comment] 2018-04-28 08:44
Thanks for the PR @dbertouille. Closing this issue now. Feel free to re-open if you don't think the issue is resolved :-)

**Closed as completed by dlebech** 2018-04-28 08:44 UTC
